name 'coralnexus-haproxy'
version '0.4.0'
source 'git://github.com/coralnexus/puppet-haproxy.git'
author 'Adrian Webb <adrian.webb@coralnexus.com>'
license 'ASL 2.0'
summary 'HAProxy module'
description 'Installs, configures, and manages the HAProxy server'
project_page 'http://github.com/coralnexus/puppet-haproxy'
dependency 'coralnexus/corl', '>= 0.4.0'